sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - pip install pip-accel
  - pip-accel install coveralls
  - pip-accel install --requirement=requirements-checks.txt
  - pip-accel install --requirement=requirements-tests.txt
  - LC_ALL=C pip-accel install .
script:
  - make check
  - py.test --cov --verbose
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
